<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ProviderProfile extends Model
{
    protected $fillable = [
        'user_id',
        'provider_type',
        'is_verified',
        'verified_at',
        'full_name',
        'national_id',
        'license_no',
        'license_expiry',
        'vehicle_type',
        'vehicle_plate',
        'vehicle_color',
        'workshop_skill',
        'workshop_skill_other',
        'workshop_category_keys',
        'workshop_neighborhood',
        'workshop_short_pitch',
        'workshop_years_experience',
        'workshop_home_visit',
        'water_capacity_liters',
        'water_has_pump',
        'water_hose_length_m',
        'water_tank_material',
        'water_pricing_mode',
        'water_price_per_tank',
        'water_price_per_liter',
        'water_min_order_liters',
        'water_service_area_keys',
        'water_potable_declared',
        'id_document_image',
        'license_image',
        'vehicle_image',
        'subscription_amount',
        'subscription_period_months',
        'subscription_starts_at',
        'subscription_ends_at',
        'subscription_status',
        'commission_rate_percent',
        'monthly_deposit_amount',
        'deposit_period_months',
        'deposit_starts_at',
        'deposit_ends_at',
        'deposit_status',
        'taxi_car_make',
        'taxi_car_model',
        'taxi_car_year',
        'taxi_seats',
        'taxi_insurance_no',
        'taxi_insurance_expiry',
        'taxi_has_ac',
        'taxi_allows_smoking',
        'taxi_is_metered',
        'taxi_base_fare',
        'taxi_price_per_km',
        'taxi_price_per_minute',
        'taxi_min_fare',
        'taxi_coverage_areas',
        'taxi_coverage_area_keys',
        'taxi_pricing_mode',
        'notes',
    ];

    protected $casts = [
        'is_verified' => 'boolean',
        'verified_at' => 'datetime',
        'license_expiry' => 'date',
        'subscription_amount' => 'decimal:2',
        'subscription_period_months' => 'integer',
        'subscription_starts_at' => 'datetime',
        'subscription_ends_at' => 'datetime',
        'commission_rate_percent' => 'decimal:2',
        'monthly_deposit_amount' => 'decimal:2',
        'deposit_period_months' => 'integer',
        'deposit_starts_at' => 'datetime',
        'deposit_ends_at' => 'datetime',
        'taxi_car_year' => 'integer',
        'taxi_seats' => 'integer',
        'taxi_insurance_expiry' => 'date',
        'taxi_has_ac' => 'boolean',
        'taxi_allows_smoking' => 'boolean',
        'taxi_is_metered' => 'boolean',
        'taxi_base_fare' => 'decimal:2',
        'taxi_price_per_km' => 'decimal:2',
        'taxi_price_per_minute' => 'decimal:2',
        'taxi_min_fare' => 'decimal:2',
        'taxi_coverage_area_keys' => 'array',
        'water_has_pump' => 'boolean',
        'water_hose_length_m' => 'integer',
        'water_price_per_tank' => 'decimal:2',
        'water_price_per_liter' => 'decimal:4',
        'water_min_order_liters' => 'integer',
        'water_service_area_keys' => 'array',
        'water_potable_declared' => 'boolean',
        'workshop_category_keys' => 'array',
        'workshop_years_experience' => 'integer',
        'workshop_home_visit' => 'boolean',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}
